name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libpthread-stubs0-dev openssl mingw-w64 
    - name: setup build environment
      run: find /usr/lib -iname 'libcrypto.a' -exec sh -c 'ln -s $(dirname "$@") ../openssl' _ {} \; -quit
    - name: build executables for Linux
      run: openssl version && ln -s Linux/Makefile && make
